name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod vendor

    - name: Go vet
      run: go vet $(go list ./... | grep -v /vendor/)

    - name: Go test
      run: go test -cpu=1,2,4 -v -tags integration ./...

    - name: Go run main.go
      run: go run main/main.go

    - name: Go get
      run: go get github.com/wuxiaoxiaoshen/fakeuseragent/application

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wuxiaoshen/fakeuseragent:$(date "+v0.%Y%m%d%H")

    - name: Docker Push
      run: docker push wuxiaoshen/fakeuseragent:$(date "+v0.%Y%m%d%H")

    - name: Echo Images
      run: docker images